version: 2

sources:
  - name: Staging
    database: Demo
    schema: Staging
    tables:
        - name: stg_opportunity
        - name: stg_opportunityhistory
        - name: stg_account
        - name: stg_opportunitylineitem
  - name: DWh
    database: Demo
    schema: DWh 
    tables:
        - name: dim_opportunity     